# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ATS
tagline:          'Art & Technology Studies'
description:      'This is the home to all of the resources ATS has to offer <a href="https://saic.edu/ats" target="_blank">@SAIC</a>.'
url:              http://atstudies.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/atstudies/
