# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            ats resource center
tagline:          'Art & Technology Studies'
description:      'This is the home to all of the resources ATS has to offer <a href="https://saic.edu/ats" target="_blank">@SAIC</a>.'
url:              http://atstudies.github.io
baseurl:          /

author:
  name:           'Michael Powell'
  url:            https://cargocollective.com/demfraga

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/atstudies/
